---
apiVersion: v1
kind: Service
metadata:
  name: mathz-databases-emailpostgres
spec:
  type: ClusterIP
  selector:
    app: mathz-databases-emailpostgres
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
