resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: tracelens-env
  literals:
    - PlantUml__RemoteUrl=plantuml:8080
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=tracelens

secretGenerator:
- name: tracelens-secrets
  envs:
  - .tracelens.secrets
