---
apiVersion: v1
kind: Service
metadata:
  name: tracelens
spec:
  type: ClusterIP
  selector:
    app: tracelens
  ports:
  - name: tracelens
    port: 5001
    targetPort: 5001
  - name: otel
    port: 4317
    targetPort: 4317
