---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathz-messagebus-rabbitmq
  labels:
    app: mathz-messagebus-rabbitmq
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: mathz-messagebus-rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mathz-messagebus-rabbitmq
    spec:
      containers:
      - name: mathz-messagebus-rabbitmq
        image: docker.io/library/rabbitmq:3.13-management
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 5672
        - name: management
          containerPort: 15672
        envFrom:
        - configMapRef:
            name: mathz-messagebus-rabbitmq-env
      terminationGracePeriodSeconds: 180