name: Build and Test AppHost

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/MathZ.AppHost/MathZ.AppHost.csproj
    - name: Build
      run: dotnet build src/MathZ.AppHost/MathZ.AppHost.csproj --no-restore
    - name: Test
      run: dotnet test src/MathZ.AppHost/MathZ.AppHost.csproj --no-build --verbosity normal
